apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-petclinic
        image: thotamanikanta23/spring-petclinic:2.0.0
        ports:
        - containerPort: 8082		
---		
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8085
      nodePort: 30007

